version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      # Replace with your actual URL in production
      url: http://localhost:2368
      database__client: pg
      database__connection__host: dpg-d1o55dripnbc7386jta0-a
      database__connection__user: fmoblog_user
      database__connection__password: C8eK3zqTqHh6iNb9oTQwFWmZxrp9fO2H
      database__connection__database: fmoblog
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      - db

  # Render provides a managed PostgreSQL database, so we don't need to run a DB container here.
  # This 'db' service is commented out because it will be replaced by Render's managed database.
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_USER: fmoblog_user
  #     POSTGRES_PASSWORD: C8eK3zqTqHh6iNb9oTQwFWmZxrp9fO2H
  #     POSTGRES_DB: fmoblog
  #   volumes:
  #     - ghost_db:/var/lib/postgresql/data

volumes:
  ghost_content:
  ghost_db:
